const getAllusers= async(req, res, next)=>{
    try {
        
    } catch (err) {
        
    }
}